env:
- _MARKDOWN=2.6.10
- _MARKDOWN=2.6.5
- _MARKDOWN=2.6.6
- _MARKDOWN=2.6.8
- _MARKDOWN=2.6.9
install:
- pip install Markdown==$_MARKDOWN
language: python
python:
- 2.7
- 3.4
- 3.5
script:
- python setup.py test
